# Generated by Django 5.0.6 on 2024-06-22 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('element', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('posted', models.DateTimeField(auto_now=True)),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='element.element')),
            ],
        ),
    ]
